# https://docs.fastlane.tools/actions/
# Change the syntax highlighting to Ruby

# update_fastlane

min_fastlane_version("2.73.0")

default_platform(:ios)

platform :ios do
  before_all do
    cocoapods
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    increment_version_number
    build_app(scheme: "Dusken") # more options available
    upload_to_testflight(skip_waiting_for_build_processing: true)
    slack(message: "Chateau Neuf app build uploaded to TestFlight")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    increment_build_number
    increment_version_number
    # capture_screenshots
    build_app(scheme: "Dusken") # more options available
    upload_to_app_store(force: true)
    # frame_screenshots
    slack(message: "Chateau Neuf app build uploaded to App Store")
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
