# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.62.1"

default_platform :android

platform :android do
  desc "Submit a new build to the Google Play Beta track"
  lane :beta do
    # build the release variant
    gradle(task: "assembleRelease")

    # upload to Google Play
    supply(track: "beta")
  end
end
