# https://docs.fastlane.tools/actions/
# Change the syntax highlighting to Ruby

# update_fastlane

fastlane_version "2.73.0"

default_platform :android

platform :android do
  desc "Submit a new build to the Google Play Beta track"
  lane :beta do
    # build the release variant
    gradle(task: "assembleRelease")

    # upload to Google Play
    supply(track: "beta")

    slack(message: "Chateau Neuf app build uploaded to Google Play")
  end
end
