# https://docs.fastlane.tools/actions/
# Change the syntax highlighting to Ruby

default_platform(:android)

platform :android do
  desc "Submit a new build to the Google Play Beta track"
  lane :beta do
    # build the release variant
    gradle(task: "bundle", build_type: "Release")

    # upload to Google Play
    upload_to_play_store(
        track: "beta",
        skip_upload_images: true,
        # Specify these to avoid `gradle clean`
        skip_upload_apk: true,
        aab: "./app/build/outputs/bundle/release/app.aab")

    slack(message: "Chateau Neuf app build uploaded to Google Play")
  end

  lane :build do
    gradle(task: "bundle", build_type: "Release")
  end
end
